### ISSUE TITLE
Invalid services.yml file

### ISSUE THREAD

**Issue by dragosvr92** [RMcGirr83/phpBB-3.1-nationalflags#23]
The **Extensions .yml Files Syntax Check** extension identifies services.yml file as invalid.... Yet i have the latest National Flags extension. 
I tried replacing the single quotes to double quotes but its still claiming the file is invalid. 

Here is my file:
```

imports:
    - { resource: tables.yml }
    - { resource: flag_constants.yml }

services:
    rmcgirr83.nationalflags.admin.controller:
        class: rmcgirr83\nationalflags\controller\admin_controller
        arguments:
            - "@cache"
            - "@config"
            - "@dbal.conn"
            - "@pagination"
            - "@controller.helper"
            - "@request"
            - "@template"
            - "@user"
            - "@log"
            - "@ext.manager"
            - "@path_helper"
            - "%core.root_path%"
            - "%core.php_ext%"
            - "%flag_constants%"
            - "%rmcgirr83.nationalflags.table.nationalflags%"
            - "@rmcgirr83.nationalflags.nationalflags"
            - "@files.factory"
            - "@filesystem"
            - "@language"

    rmcgirr83.nationalflags.main.controller:
        class: rmcgirr83\nationalflags\controller\main_controller
        arguments:
            - "@auth"
            - "@config"
            - "@dbal.conn"
            - "@pagination"
            - "@controller.helper"
            - "@language"
            - "@request"
            - "@ext.manager"
            - "@path_helper"
            - "@template"
            - "@user"
            - "%core.root_path%"
            - "%core.php_ext%"
            - "%rmcgirr83.nationalflags.table.nationalflags%"
            - "@rmcgirr83.nationalflags.nationalflags"
            - "@files.factory"

    rmcgirr83.nationalflags.listener:
        class: rmcgirr83\nationalflags\event\listener
        arguments:
            - "@auth"
            - "@config"
            - "@controller.helper"
            - "@dbal.conn"
            - "@language"
            - "@request"
            - "@template"
            - "@user"
            - "@ext.manager"
            - "%core.root_path%"
            - "%core.php_ext%"
            - "@rmcgirr83.nationalflags.nationalflags"
        tags:
            - { name: event.listener }

    rmcgirr83.nationalflags.nationalflags:
        class: rmcgirr83\nationalflags\core\nationalflags
        arguments:
            - "@config"
            - "@controller.helper"
            - "@cache"
            - "@dbal.conn"
            - "@language"
            - "@template"
            - "@user"
            - "%rmcgirr83.nationalflags.table.nationalflags%"
            - "@ext.manager"
            - "@path_helper"
            - %flag_constants%
            - "@?phpbb.collapsiblecategories.operator"

```
